using Josephus;

namespace JosephusTest
{
    internal class JosephusTest
    {

        [TestCaseSource(nameof(GoldenMaster))]
        public void JoesphusTest(int actual, int expected)
        {
            Assert.That(JosephusGood.GetSolution(actual), Is.EqualTo(expected));
        }

        static object[] GoldenMaster =
        {
            new object[]{ 0, 0 },
            new object[]{ 1, 0 },
            new object[]{ 2, 1 },
            new object[]{ 3, 1 },
            new object[]{ 4, 0 },
            new object[]{ 5, 3 },
            new object[]{ 6, 0 },
            new object[]{ 7, 3 },
            new object[]{ 8, 6 },
            new object[]{ 9, 0 },
            new object[]{ 10, 3 },
            new object[]{ 11, 6 },
            new object[]{ 12, 9 },
            new object[]{ 13, 12 },
            new object[]{ 14, 1 },
            new object[]{ 15, 4 },
            new object[]{ 16, 7 },
            new object[]{ 17, 10 },
            new object[]{ 18, 13 },
            new object[]{ 19, 16 },
            new object[]{ 20, 19 },
            new object[]{ 21, 1 },
            new object[]{ 22, 4 },
            new object[]{ 23, 7 },
            new object[]{ 24, 10 },
            new object[]{ 25, 13 },
            new object[]{ 26, 16 },
            new object[]{ 27, 19 },
            new object[]{ 28, 22 },
            new object[]{ 29, 25 },
            new object[]{ 30, 28 },
            new object[]{ 31, 0 },
            new object[]{ 32, 3 },
            new object[]{ 33, 6 },
            new object[]{ 34, 9 },
            new object[]{ 35, 12 },
            new object[]{ 36, 15 },
            new object[]{ 37, 18 },
            new object[]{ 38, 21 },
            new object[]{ 39, 24 },
            new object[]{ 40, 27 },
            new object[]{ 41, 30 },
            new object[]{ 42, 33 },
            new object[]{ 43, 36 },
            new object[]{ 44, 39 },
            new object[]{ 45, 42 },
            new object[]{ 46, 45 },
            new object[]{ 47, 1 },
            new object[]{ 48, 4 },
            new object[]{ 49, 7 },
            new object[]{ 50, 10 },
            new object[]{ 51, 13 },
            new object[]{ 52, 16 },
            new object[]{ 53, 19 },
            new object[]{ 54, 22 },
            new object[]{ 55, 25 },
            new object[]{ 56, 28 },
            new object[]{ 57, 31 },
            new object[]{ 58, 34 },
            new object[]{ 59, 37 },
            new object[]{ 60, 40 },
            new object[]{ 61, 43 },
            new object[]{ 62, 46 },
            new object[]{ 63, 49 },
            new object[]{ 64, 52 },
            new object[]{ 65, 55 },
            new object[]{ 66, 58 },
            new object[]{ 67, 61 },
            new object[]{ 68, 64 },
            new object[]{ 69, 67 },
            new object[]{ 70, 0 },
            new object[]{ 71, 3 },
            new object[]{ 72, 6 },
            new object[]{ 73, 9 },
            new object[]{ 74, 12 },
            new object[]{ 75, 15 },
            new object[]{ 76, 18 },
            new object[]{ 77, 21 },
            new object[]{ 78, 24 },
            new object[]{ 79, 27 },
            new object[]{ 80, 30 },
            new object[]{ 81, 33 },
            new object[]{ 82, 36 },
            new object[]{ 83, 39 },
            new object[]{ 84, 42 },
            new object[]{ 85, 45 },
            new object[]{ 86, 48 },
            new object[]{ 87, 51 },
            new object[]{ 88, 54 },
            new object[]{ 89, 57 },
            new object[]{ 90, 60 },
            new object[]{ 91, 63 },
            new object[]{ 92, 66 },
            new object[]{ 93, 69 },
            new object[]{ 94, 72 },
            new object[]{ 95, 75 },
            new object[]{ 96, 78 },
            new object[]{ 97, 81 },
            new object[]{ 98, 84 },
            new object[]{ 99, 87 }
        };

    }
}